### ISSUE TITLE
dataset link invalid

### ISSUE THREAD

**Issue by Pieux0** [haoosz/ade-czsl#5]
Thanks for your nice work! 
I met the problem when download the dataset files: this link https://www.cs.utexas.edu/~tushar/attribute-ops/attr-ops-data.tar.gz is not accessible now. Could you provide a updated one?

**Comment by haoosz** [comment]
Hi, try this link out: [https://utexas.box.com/shared/static/h7ckk2gx5ykw53h8o641no8rdyi7185g.gz](https://utexas.box.com/shared/static/h7ckk2gx5ykw53h8o641no8rdyi7185g.gz)

I commit e97df2d to solve this. This data download script is borrowed from [this repo](https://github.com/Tushar-N/attributes-as-operators), and `attr-ops-data.tar.gz` is their pretrained model and preprocessed data, which we don't use in this work.

**Comment by Pieux0** [comment]
Thanks a lot. I already got the dataset successfully.

**Comment by haoosz** [comment]
Good!
